package com.scms.scms.model;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Entity
@Table(name = "exam_session")
public class ExamSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;

    private String subject;

    @Column(length = 2000)
    private String syllabusTopics;

    @Column(length = 2000)
    private String instructions;

    @Column(length = 2000)
    private String seatingInfo;

    @Column(name = "exam_date_time")
    private LocalDateTime examDateTime;

    @Column(name = "duration_minutes")
    private Integer durationMinutes;

    private String room;

    @Column(name = "syllabus_original_file_name")
    private String syllabusOriginalFileName;

    @Column(name = "syllabus_stored_file_name")
    private String syllabusStoredFileName;

    @Column(name = "syllabus_file_path")
    private String syllabusFilePath;

    @Column(name = "syllabus_content_type")
    private String syllabusContentType;

    @Column(name = "syllabus_file_size")
    private Long syllabusFileSize;

    @Column(name = "status")
    private String status;

    @Column(name = "exam_mode")
    private String examMode;

    @Column(name = "quiz_question_count")
    private Integer quizQuestionCount;

    @Column(name = "quiz_auto_generated")
    private Boolean quizAutoGenerated;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "finalized_at")
    private LocalDateTime finalizedAt;

    @ManyToOne
    @JoinColumn(name = "teacher_id")
    private Teacher teacher;

    @ManyToOne
    @JoinColumn(name = "class_room_id")
    private ClassRoom classRoom;

    @ManyToOne
    @JoinColumn(name = "admin_id")
    private Admin admin;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getSubject() { return subject; }
    public void setSubject(String subject) { this.subject = subject; }
    public String getSyllabusTopics() { return syllabusTopics; }
    public void setSyllabusTopics(String syllabusTopics) { this.syllabusTopics = syllabusTopics; }
    public String getInstructions() { return instructions; }
    public void setInstructions(String instructions) { this.instructions = instructions; }
    public String getSeatingInfo() { return seatingInfo; }
    public void setSeatingInfo(String seatingInfo) { this.seatingInfo = seatingInfo; }
    public LocalDateTime getExamDateTime() { return examDateTime; }
    public void setExamDateTime(LocalDateTime examDateTime) { this.examDateTime = examDateTime; }
    public Integer getDurationMinutes() { return durationMinutes; }
    public void setDurationMinutes(Integer durationMinutes) { this.durationMinutes = durationMinutes; }
    public String getRoom() { return room; }
    public void setRoom(String room) { this.room = room; }
    public String getSyllabusOriginalFileName() { return syllabusOriginalFileName; }
    public void setSyllabusOriginalFileName(String syllabusOriginalFileName) { this.syllabusOriginalFileName = syllabusOriginalFileName; }
    public String getSyllabusStoredFileName() { return syllabusStoredFileName; }
    public void setSyllabusStoredFileName(String syllabusStoredFileName) { this.syllabusStoredFileName = syllabusStoredFileName; }
    public String getSyllabusFilePath() { return syllabusFilePath; }
    public void setSyllabusFilePath(String syllabusFilePath) { this.syllabusFilePath = syllabusFilePath; }
    public String getSyllabusContentType() { return syllabusContentType; }
    public void setSyllabusContentType(String syllabusContentType) { this.syllabusContentType = syllabusContentType; }
    public Long getSyllabusFileSize() { return syllabusFileSize; }
    public void setSyllabusFileSize(Long syllabusFileSize) { this.syllabusFileSize = syllabusFileSize; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public String getExamMode() { return examMode; }
    public void setExamMode(String examMode) { this.examMode = examMode; }
    public Integer getQuizQuestionCount() { return quizQuestionCount; }
    public void setQuizQuestionCount(Integer quizQuestionCount) { this.quizQuestionCount = quizQuestionCount; }
    public Boolean getQuizAutoGenerated() { return quizAutoGenerated; }
    public void setQuizAutoGenerated(Boolean quizAutoGenerated) { this.quizAutoGenerated = quizAutoGenerated; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    public LocalDateTime getFinalizedAt() { return finalizedAt; }
    public void setFinalizedAt(LocalDateTime finalizedAt) { this.finalizedAt = finalizedAt; }
    public Teacher getTeacher() { return teacher; }
    public void setTeacher(Teacher teacher) { this.teacher = teacher; }
    public ClassRoom getClassRoom() { return classRoom; }
    public void setClassRoom(ClassRoom classRoom) { this.classRoom = classRoom; }
    public Admin getAdmin() { return admin; }
    public void setAdmin(Admin admin) { this.admin = admin; }

    @Transient
    public String getExamDateLabel() {
        return examDateTime != null ? examDateTime.format(DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a")) : "TBD";
    }

    @Transient
    public String getDurationLabel() {
        if (durationMinutes == null || durationMinutes <= 0) {
            return "Duration not set";
        }
        return durationMinutes + " min";
    }

    @Transient
    public String getStatusLabel() {
        return status != null && !status.isBlank() ? status : "Scheduled";
    }

    @Transient
    public boolean isQuiz() {
        return "QUIZ".equalsIgnoreCase(examMode);
    }

    @Transient
    public String getExamModeLabel() {
        return isQuiz() ? "Online Quiz" : "Standard Exam";
    }

    @Transient
    public boolean isCompleted() {
        return "COMPLETED".equalsIgnoreCase(status);
    }

    @Transient
    public String getSyllabusDownloadName() {
        return syllabusOriginalFileName != null && !syllabusOriginalFileName.isBlank()
                ? syllabusOriginalFileName
                : "syllabus";
    }
}
