package com.scms.scms.service;

import com.scms.scms.model.*;
import com.scms.scms.repository.*;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.*;
import java.util.regex.Pattern;

@Service
public class ExamAutomationService {

    private static final Path STATIC_ROOT = Paths.get(System.getProperty("user.dir"), "src", "main", "resources", "static");
    private static final String EXAM_UPLOAD_DIR = "uploads/exams/";

    @Autowired private ExamSessionRepository examSessionRepository;
    @Autowired private ExamAttendanceRepository examAttendanceRepository;
    @Autowired private PortalNotificationRepository portalNotificationRepository;
    @Autowired private StudentRepository studentRepository;
    @Autowired private TeacherAttendanceEntryRepository teacherAttendanceEntryRepository;
    @Autowired private AssignmentRepository assignmentRepository;
    @Autowired private StudyMaterialRepository studyMaterialRepository;
    @Autowired private ClassRoomRepository classRoomRepository;
    @Autowired private TimetableRepository timetableRepository;
    @Autowired private ExamQuizQuestionRepository examQuizQuestionRepository;
    @Autowired private ExamQuizAttemptRepository examQuizAttemptRepository;
    @Autowired private ExamQuizResponseRepository examQuizResponseRepository;

    @Transactional
    public ExamSession createExam(Teacher teacher,
                                  String title,
                                  String subject,
                                  String syllabusTopics,
                                  String instructions,
                                  String seatingInfo,
                                  LocalDateTime examDateTime,
                                  Integer durationMinutes,
                                  String room,
                                  MultipartFile syllabusFile) {
        ClassRoom resolvedClassRoom = resolveTeacherClassRoom(teacher);
        ExamSession exam = new ExamSession();
        exam.setTeacher(teacher);
        exam.setClassRoom(resolvedClassRoom);
        exam.setAdmin(teacher != null ? teacher.getAdmin() : null);
        exam.setTitle(clean(title, "Untitled exam"));
        exam.setSubject(clean(subject, clean(teacher != null ? teacher.getSubject() : null, "Subject")));
        exam.setSyllabusTopics(clean(syllabusTopics, "Topics will be shared soon"));
        exam.setInstructions(clean(instructions, "Follow the teacher instructions."));
        exam.setSeatingInfo(clean(seatingInfo, "Seating will be generated by the system."));
        exam.setExamDateTime(examDateTime);
        exam.setDurationMinutes(durationMinutes != null && durationMinutes > 0 ? durationMinutes : 60);
        exam.setRoom(clean(room, resolvedClassRoom != null ? resolvedClassRoom.getRoom() : "TBD"));
        exam.setStatus("SCHEDULED");
        exam.setExamMode("STANDARD");
        exam.setQuizQuestionCount(0);
        exam.setQuizAutoGenerated(Boolean.FALSE);
        exam.setCreatedAt(LocalDateTime.now());
        exam.setUpdatedAt(LocalDateTime.now());

        if (syllabusFile != null && !syllabusFile.isEmpty()) {
            StoredFile storedFile = storeExamFile(syllabusFile);
            if (storedFile != null) {
                exam.setSyllabusOriginalFileName(storedFile.originalName());
                exam.setSyllabusStoredFileName(storedFile.storedName());
                exam.setSyllabusFilePath(storedFile.webPath());
                exam.setSyllabusContentType(storedFile.contentType());
                exam.setSyllabusFileSize(storedFile.size());
            }
        }

        exam = examSessionRepository.save(exam);
        createExamNotifications(exam, teacher);
        createPendingExamAttendance(exam);
        return exam;
    }

    @Transactional
    public ExamSession createQuizExam(Teacher teacher,
                                      String title,
                                      String subject,
                                      String instructions,
                                      LocalDateTime examDateTime,
                                      Integer durationMinutes,
                                      MultipartFile pdfFile,
                                      Integer questionCount) {
        if (teacher == null || pdfFile == null || pdfFile.isEmpty()) {
            return null;
        }
        String fileName = Objects.requireNonNullElse(pdfFile.getOriginalFilename(), "").toLowerCase(Locale.ENGLISH);
        if (!fileName.endsWith(".pdf")) {
            return null;
        }

        ClassRoom resolvedClassRoom = resolveTeacherClassRoom(teacher);
        String extractedText = extractPdfText(pdfFile);
        List<GeneratedQuestion> generatedQuestions = generateQuizQuestions(
                extractedText,
                Math.max(3, Math.min(questionCount != null ? questionCount : 10, 25))
        );
        if (generatedQuestions.size() < 3) {
            return null;
        }

        ExamSession exam = new ExamSession();
        exam.setTeacher(teacher);
        exam.setClassRoom(resolvedClassRoom);
        exam.setAdmin(teacher.getAdmin());
        exam.setTitle(clean(title, "Online Quiz"));
        exam.setSubject(clean(subject, clean(teacher.getSubject(), "Subject")));
        exam.setSyllabusTopics("Auto-generated MCQ quiz from uploaded PDF notes.");
        exam.setInstructions(clean(instructions, "Read every MCQ carefully. The quiz auto-submits when the timer ends."));
        exam.setSeatingInfo("Online quiz");
        exam.setExamDateTime(examDateTime);
        exam.setDurationMinutes(durationMinutes != null && durationMinutes > 0 ? durationMinutes : 20);
        exam.setRoom("Online Quiz");
        exam.setStatus("SCHEDULED");
        exam.setExamMode("QUIZ");
        exam.setQuizQuestionCount(generatedQuestions.size());
        exam.setQuizAutoGenerated(Boolean.TRUE);
        exam.setCreatedAt(LocalDateTime.now());
        exam.setUpdatedAt(LocalDateTime.now());

        StoredFile storedFile = storeExamFile(pdfFile);
        if (storedFile == null) {
            return null;
        }
        exam.setSyllabusOriginalFileName(storedFile.originalName());
        exam.setSyllabusStoredFileName(storedFile.storedName());
        exam.setSyllabusFilePath(storedFile.webPath());
        exam.setSyllabusContentType(storedFile.contentType());
        exam.setSyllabusFileSize(storedFile.size());

        exam = examSessionRepository.save(exam);
        int order = 1;
        for (GeneratedQuestion generatedQuestion : generatedQuestions) {
            ExamQuizQuestion question = new ExamQuizQuestion();
            question.setExamSession(exam);
            question.setQuestionOrder(order++);
            question.setQuestionText(generatedQuestion.questionText());
            question.setOptionA(generatedQuestion.optionA());
            question.setOptionB(generatedQuestion.optionB());
            question.setOptionC(generatedQuestion.optionC());
            question.setOptionD(generatedQuestion.optionD());
            question.setCorrectOption(generatedQuestion.correctOption());
            question.setExplanation(generatedQuestion.explanation());
            examQuizQuestionRepository.save(question);
        }

        createExamNotifications(exam, teacher);
        return exam;
    }

    public List<ExamSession> findTeacherExams(Teacher teacher) {
        if (teacher == null) {
            return List.of();
        }

        List<ExamSession> exams = new ArrayList<>();
        ClassRoom classRoom = resolveTeacherClassRoom(teacher);
        if (classRoom != null) {
            exams.addAll(examSessionRepository.findByClassRoomOrderByExamDateTimeAsc(classRoom));
        }
        if (exams.isEmpty() && teacher.getAdmin() != null) {
            exams.addAll(examSessionRepository.findByAdminOrderByExamDateTimeDesc(teacher.getAdmin()));
        }
        if (exams.isEmpty()) {
            exams.addAll(examSessionRepository.findByTeacherOrderByExamDateTimeDesc(teacher));
        }
        return exams.stream()
                .filter(exam -> exam.getTeacher() == null || teacher.getId() == null || teacher.getId().equals(exam.getTeacher().getId()))
                .distinct()
                .sorted(Comparator.comparing(ExamSession::getExamDateTime, Comparator.nullsLast(Comparator.naturalOrder())).reversed())
                .toList();
    }

    public List<ExamSession> findTeacherStandardExams(Teacher teacher) {
        return findTeacherExams(teacher).stream()
                .filter(exam -> !exam.isQuiz())
                .toList();
    }

    public List<ExamSession> findTeacherQuizExams(Teacher teacher) {
        return findTeacherExams(teacher).stream()
                .filter(ExamSession::isQuiz)
                .toList();
    }

    public List<ExamSession> findStudentExams(Student student) {
        if (student == null) {
            return List.of();
        }

        ClassRoom classRoom = student.getClassRoom();
        LinkedHashMap<Long, ExamSession> visible = new LinkedHashMap<>();
        List<ExamSession> exams = classRoom != null
                ? examSessionRepository.findByClassRoomOrderByExamDateTimeAsc(classRoom)
                : student.getAdmin() != null ? examSessionRepository.findByAdminOrderByExamDateTimeDesc(student.getAdmin()) : List.of();
        for (ExamSession exam : exams) {
            if (exam != null && exam.getId() != null) {
                visible.putIfAbsent(exam.getId(), exam);
            }
        }
        if (student.getAdmin() != null) {
            for (ExamSession exam : examSessionRepository.findByAdminOrderByExamDateTimeDesc(student.getAdmin())) {
                if (exam == null || exam.getId() == null || exam.getTeacher() == null) {
                    continue;
                }
                ClassRoom teacherClassRoom = resolveTeacherClassRoom(exam.getTeacher());
                if (teacherClassRoom != null && classRoom != null
                        && Objects.equals(teacherClassRoom.getId(), classRoom.getId())) {
                    visible.putIfAbsent(exam.getId(), exam);
                }
            }
        }
        return visible.values().stream()
                .filter(exam -> exam.getStatus() == null || !"CANCELLED".equalsIgnoreCase(exam.getStatus()))
                .sorted(Comparator.comparing(ExamSession::getExamDateTime, Comparator.nullsLast(Comparator.naturalOrder())))
                .toList();
    }

    public List<ExamSession> findStudentStandardExams(Student student) {
        return findStudentExams(student).stream()
                .filter(exam -> !exam.isQuiz())
                .toList();
    }

    public List<ExamSession> findStudentQuizzes(Student student) {
        return findStudentExams(student).stream()
                .filter(ExamSession::isQuiz)
                .toList();
    }

    public List<ExamQuizQuestion> findQuizQuestions(ExamSession examSession) {
        if (examSession == null || !examSession.isQuiz()) {
            return List.of();
        }
        return examQuizQuestionRepository.findByExamSessionOrderByQuestionOrderAsc(examSession);
    }

    public ExamQuizAttempt findQuizAttempt(ExamSession examSession, Student student) {
        if (examSession == null || student == null) {
            return null;
        }
        return examQuizAttemptRepository.findByExamSessionAndStudent(examSession, student).orElse(null);
    }

    public List<ExamQuizResponse> findQuizResponses(ExamQuizAttempt attempt) {
        if (attempt == null) {
            return List.of();
        }
        return examQuizResponseRepository.findByAttemptOrderByQuestion_QuestionOrderAsc(attempt);
    }

    public List<ExamQuizAttempt> findQuizAttemptsForTeacher(ExamSession examSession, Teacher teacher) {
        if (examSession == null || teacher == null || examSession.getTeacher() == null
                || !Objects.equals(examSession.getTeacher().getId(), teacher.getId())) {
            return List.of();
        }
        return examQuizAttemptRepository.findByExamSessionOrderBySubmittedAtDesc(examSession);
    }

    @Transactional
    public ExamQuizAttempt startQuizAttempt(ExamSession examSession, Student student) {
        if (examSession == null || student == null || !examSession.isQuiz() || !isQuizAvailableForStudent(examSession, student)) {
            return null;
        }
        ExamQuizAttempt existing = findQuizAttempt(examSession, student);
        if (existing != null) {
            if (existing.isSubmitted()) {
                return existing;
            }
            if (existing.getStartedAt() == null) {
                existing.setStartedAt(LocalDateTime.now());
                existing.setStatus("IN_PROGRESS");
                return examQuizAttemptRepository.save(existing);
            }
            return existing;
        }

        ExamQuizAttempt attempt = new ExamQuizAttempt();
        attempt.setExamSession(examSession);
        attempt.setStudent(student);
        attempt.setAdmin(student.getAdmin());
        attempt.setStartedAt(LocalDateTime.now());
        attempt.setStatus("IN_PROGRESS");
        attempt.setTotalQuestions((int) examQuizQuestionRepository.countByExamSession(examSession));
        attempt.setScore(0);
        attempt.setCorrectAnswers(0);
        attempt.setAutoSubmitted(Boolean.FALSE);
        return examQuizAttemptRepository.save(attempt);
    }

    @Transactional
    public ExamQuizAttempt submitQuizAttempt(ExamSession examSession,
                                             Student student,
                                             Map<Long, String> answers,
                                             boolean autoSubmitted) {
        if (examSession == null || student == null || !examSession.isQuiz()) {
            return null;
        }
        ExamQuizAttempt attempt = findQuizAttempt(examSession, student);
        if (attempt == null) {
            attempt = startQuizAttempt(examSession, student);
        }
        if (attempt == null || attempt.isSubmitted()) {
            return attempt;
        }

        List<ExamQuizQuestion> questions = findQuizQuestions(examSession);
        int correctAnswers = 0;
        for (ExamQuizQuestion question : questions) {
            String selectedOption = normalizeOption(answers.get(question.getId()));
            boolean correct = selectedOption != null && selectedOption.equalsIgnoreCase(question.getCorrectOption());
            if (correct) {
                correctAnswers++;
            }
            ExamQuizResponse response = examQuizResponseRepository.findByAttemptAndQuestion(attempt, question)
                    .orElseGet(ExamQuizResponse::new);
            response.setAttempt(attempt);
            response.setQuestion(question);
            response.setSelectedOption(selectedOption);
            response.setCorrectOption(question.getCorrectOption());
            response.setCorrect(correct);
            examQuizResponseRepository.save(response);
        }

        attempt.setCorrectAnswers(correctAnswers);
        attempt.setTotalQuestions(questions.size());
        attempt.setScore(correctAnswers);
        attempt.setSubmittedAt(LocalDateTime.now());
        attempt.setStatus("SUBMITTED");
        attempt.setAutoSubmitted(autoSubmitted);
        return examQuizAttemptRepository.save(attempt);
    }

    public List<PortalNotification> findVisibleNotifications(String role, String email) {
        if (role == null || email == null) {
            return List.of();
        }
        return portalNotificationRepository
                .findByRecipientRoleAndRecipientEmailAndScheduledForLessThanEqualOrderByCreatedAtDesc(role, email, LocalDateTime.now());
    }

    public long countUnreadNotifications(String role, String email) {
        if (role == null || email == null) {
            return 0L;
        }
        return portalNotificationRepository.countByRecipientRoleAndRecipientEmailAndScheduledForLessThanEqualAndReadAtIsNull(role, email, LocalDateTime.now());
    }

    @Transactional
    public void markAllNotificationsRead(String role, String email) {
        List<PortalNotification> notifications = portalNotificationRepository
                .findByRecipientRoleAndRecipientEmailAndScheduledForLessThanEqualOrderByCreatedAtDesc(role, email, LocalDateTime.now());
        LocalDateTime now = LocalDateTime.now();
        notifications.stream()
                .filter(PortalNotification::isUnread)
                .forEach(notification -> notification.setReadAt(now));
        portalNotificationRepository.saveAll(notifications);
    }

    public List<ExamAttendance> getAttendance(ExamSession examSession) {
        if (examSession == null) {
            return List.of();
        }
        return examAttendanceRepository.findByExamSessionOrderByStudent_NameAsc(examSession);
    }

    public ExamSession findExam(Long examId) {
        if (examId == null) {
            return null;
        }
        return examSessionRepository.findById(examId).orElse(null);
    }

    @Transactional
    public void saveAttendance(ExamSession examSession, Map<Long, String> statuses) {
        if (examSession == null || statuses == null || statuses.isEmpty()) {
            return;
        }

        LocalDateTime now = LocalDateTime.now();
        for (Map.Entry<Long, String> entry : statuses.entrySet()) {
            Long studentId = entry.getKey();
            String status = clean(entry.getValue(), "PENDING").toUpperCase(Locale.ENGLISH);
            Student student = studentRepository.findById(studentId).orElse(null);
            if (student == null) {
                continue;
            }

            ExamAttendance attendance = examAttendanceRepository.findByExamSessionAndStudent(examSession, student);
            if (attendance == null) {
                attendance = new ExamAttendance();
                attendance.setExamSession(examSession);
                attendance.setStudent(student);
            }
            attendance.setStatus(status);
            attendance.setAutoMarked(false);
            attendance.setMarkedAt(now);
            examAttendanceRepository.save(attendance);
        }
    }

    @Transactional
    public void createPendingExamAttendance(ExamSession examSession) {
        if (examSession == null || examSession.getClassRoom() == null) {
            return;
        }

        List<Student> students = studentRepository.findByClassRoom(examSession.getClassRoom());
        for (Student student : students) {
            if (examAttendanceRepository.findByExamSessionAndStudent(examSession, student) != null) {
                continue;
            }
            ExamAttendance attendance = new ExamAttendance();
            attendance.setExamSession(examSession);
            attendance.setStudent(student);
            attendance.setStatus("PENDING");
            attendance.setAutoMarked(false);
            attendance.setMarkedAt(null);
            examAttendanceRepository.save(attendance);
        }
    }

    @Transactional
    public void finalizeOverdueExams() {
        LocalDateTime now = LocalDateTime.now();
        List<ExamSession> overdue = examSessionRepository
                .findByExamDateTimeBeforeAndStatusNotIn(now, List.of("COMPLETED", "CANCELLED"));

        for (ExamSession exam : overdue) {
            List<ExamAttendance> attendanceRows = examAttendanceRepository.findByExamSessionOrderByStudent_NameAsc(exam);
            for (ExamAttendance row : attendanceRows) {
                if (row.getStatus() == null || row.getStatus().isBlank() || "PENDING".equalsIgnoreCase(row.getStatus())) {
                    row.setStatus("ABSENT");
                    row.setAutoMarked(true);
                    row.setMarkedAt(now);
                }
            }
            exam.setStatus("COMPLETED");
            exam.setFinalizedAt(now);
            exam.setUpdatedAt(now);
            examSessionRepository.save(exam);
            examAttendanceRepository.saveAll(attendanceRows);
        }
    }

    @Transactional
    public void createExamNotifications(ExamSession exam, Teacher teacher) {
        if (exam == null) {
            return;
        }

        List<Student> students = exam.getClassRoom() != null
                ? studentRepository.findByClassRoom(exam.getClassRoom())
                : List.of();
        String classLabel = exam.getClassRoom() != null ? exam.getClassRoom().getDisplayLabel() : "your class";
        String examLink = "/teacher-exams";
        String studentLink = "/exams";
        LocalDateTime now = LocalDateTime.now();

        addNotification("TEACHER",
                teacher != null ? teacher.getEmail() : null,
                "Exam scheduled: " + exam.getTitle(),
                "Your exam for " + classLabel + " is scheduled on " + exam.getExamDateLabel() + ".",
                "EXAM",
                examLink,
                "ExamSession",
                exam.getId(),
                now);

        if (teacher != null && teacher.getEmail() != null) {
            addNotification("TEACHER",
                    teacher.getEmail(),
                    "Reminder: exam starts in 24 hours",
                    "A reminder has been reserved for " + exam.getTitle() + ".",
                    "REMINDER",
                    examLink,
                    "ExamSession",
                    exam.getId(),
                    exam.getExamDateTime() != null ? exam.getExamDateTime().minusHours(24) : now);

            addNotification("TEACHER",
                    teacher.getEmail(),
                    "Reminder: exam starts in 1 hour",
                    "Final preparation reminder for " + exam.getTitle() + ".",
                    "REMINDER",
                    examLink,
                    "ExamSession",
                    exam.getId(),
                    exam.getExamDateTime() != null ? exam.getExamDateTime().minusHours(1) : now);
        }

        for (Student student : students) {
            if (student.getEmail() == null || student.getEmail().isBlank()) {
                continue;
            }

            addNotification("STUDENT",
                    student.getEmail(),
                    "New exam: " + exam.getTitle(),
                    "Your class has a scheduled exam on " + exam.getExamDateLabel() + " in " + clean(exam.getRoom(), "TBD") + ".",
                    "EXAM",
                    studentLink,
                    "ExamSession",
                    exam.getId(),
                    now);

            if (exam.getExamDateTime() != null) {
                addNotification("STUDENT",
                        student.getEmail(),
                        "Exam reminder: 24 hours left",
                        "Please review the syllabus and instructions for " + exam.getTitle() + ".",
                        "REMINDER",
                        studentLink,
                        "ExamSession",
                        exam.getId(),
                        exam.getExamDateTime().minusHours(24));

                addNotification("STUDENT",
                        student.getEmail(),
                        "Exam reminder: 1 hour left",
                        "Your exam for " + exam.getTitle() + " starts in one hour.",
                        "REMINDER",
                        studentLink,
                        "ExamSession",
                        exam.getId(),
                        exam.getExamDateTime().minusHours(1));
            }
        }
    }

    public List<StudentRiskView> buildRiskViews(Teacher teacher) {
        List<Student> students = resolveTeacherStudents(teacher);
        ClassRoom classRoom = resolveTeacherClassRoom(teacher);
        List<Assignment> assignments = classRoom != null
                ? assignmentRepository.findByClassRoomOrderByDueDateAscCreatedAtDesc(classRoom)
                : List.of();
        int openAssignments = (int) assignments.stream().filter(a -> a.isPublished() && (a.getDueDate() == null || !a.getDueDate().isBefore(java.time.LocalDate.now()))).count();
        int materialCount = classRoom != null
                ? studyMaterialRepository.findByClassRoomOrderByUploadedAtDesc(classRoom).size()
                : 0;

        List<StudentRiskView> riskViews = new ArrayList<>();
        for (Student student : students) {
            double attendanceScore = estimateAttendanceScore(student);
            double examPresencePenalty = estimateExamAbsencePenalty(student);
            double classLoadPenalty = Math.min(openAssignments * 3.0, 12.0);
            double materialPenalty = materialCount == 0 ? 6.0 : 0.0;

            double score = 100.0 - (100.0 - attendanceScore) - examPresencePenalty - classLoadPenalty - materialPenalty;
            score = Math.max(0, Math.min(100, score));

            List<String> reasons = new ArrayList<>();
            reasons.add("Attendance score: " + Math.round(attendanceScore) + "%");
            if (examPresencePenalty > 0) {
                reasons.add("Missing exam attendance records: -" + Math.round(examPresencePenalty));
            }
            if (openAssignments > 0) {
                reasons.add("Class assignment load: " + openAssignments + " open");
            }
            if (materialCount == 0) {
                reasons.add("No study materials uploaded for the class yet");
            }

            riskViews.add(new StudentRiskView(
                    student,
                    Math.round(score),
                    score >= 75 ? "Low" : score >= 50 ? "Medium" : "High",
                    String.join("; ", reasons)
            ));
        }

        return riskViews.stream()
                .sorted(Comparator.comparingLong(StudentRiskView::score))
                .toList();
    }

    public List<StudentSeatView> buildSeatingPlan(ExamSession examSession) {
        if (examSession == null || examSession.getClassRoom() == null) {
            return List.of();
        }
        List<Student> students = new ArrayList<>(studentRepository.findByClassRoom(examSession.getClassRoom()));
        students.sort(Comparator.comparing(student -> clean(student.getRollNo(), student.getName()), String.CASE_INSENSITIVE_ORDER));
        List<StudentSeatView> seats = new ArrayList<>();
        for (int i = 0; i < students.size(); i++) {
            Student student = students.get(i);
            seats.add(new StudentSeatView(i + 1, student, clean(student.getRollNo(), "N/A"), seatLabel(i + 1)));
        }
        return seats;
    }

    public List<ExamSession> findVisibleUpcomingExams(Student student) {
        return findStudentStandardExams(student).stream()
                .filter(exam -> exam.getExamDateTime() == null || exam.getExamDateTime().isAfter(LocalDateTime.now().minusMinutes(1)))
                .toList();
    }

    public List<ExamSession> findVisibleUpcomingQuizzes(Student student) {
        return findStudentQuizzes(student).stream()
                .filter(exam -> exam.getExamDateTime() == null || exam.getExamDateTime().plusMinutes(Optional.ofNullable(exam.getDurationMinutes()).orElse(20)).isAfter(LocalDateTime.now()))
                .toList();
    }

    public boolean isQuizAvailableForStudent(ExamSession examSession, Student student) {
        if (examSession == null || student == null || !examSession.isQuiz()) {
            return false;
        }
        if ("CANCELLED".equalsIgnoreCase(examSession.getStatus())) {
            return false;
        }
        boolean visible = findStudentQuizzes(student).stream()
                .anyMatch(exam -> exam.getId() != null && exam.getId().equals(examSession.getId()));
        if (!visible) {
            return false;
        }
        return examQuizQuestionRepository.countByExamSession(examSession) > 0;
    }

    public LocalDateTime quizEndTime(ExamSession examSession) {
        if (examSession == null || examSession.getExamDateTime() == null) {
            return null;
        }
        return examSession.getExamDateTime().plusMinutes(Optional.ofNullable(examSession.getDurationMinutes()).orElse(20));
    }

    public long quizRemainingSeconds(ExamSession examSession) {
        LocalDateTime end = quizEndTime(examSession);
        if (end == null) {
            return Optional.ofNullable(examSession)
                    .map(ExamSession::getDurationMinutes)
                    .filter(duration -> duration > 0)
                    .orElse(20) * 60L;
        }
        return Math.max(0L, java.time.Duration.between(LocalDateTime.now(), end).getSeconds());
    }

    public long quizRemainingSeconds(ExamSession examSession, ExamQuizAttempt attempt) {
        int durationMinutes = Optional.ofNullable(examSession)
                .map(ExamSession::getDurationMinutes)
                .filter(duration -> duration > 0)
                .orElse(20);
        if (attempt == null || attempt.getStartedAt() == null) {
            return durationMinutes * 60L;
        }
        if (attempt.isSubmitted()) {
            return 0L;
        }
        LocalDateTime end = attempt.getStartedAt().plusMinutes(durationMinutes);
        return Math.max(0L, java.time.Duration.between(LocalDateTime.now(), end).getSeconds());
    }

    private String extractPdfText(MultipartFile file) {
        try (PDDocument document = PDDocument.load(file.getBytes())) {
            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(document);
            return text != null ? text.replaceAll("\\s+", " ").trim() : "";
        } catch (IOException ex) {
            return "";
        }
    }

    private List<GeneratedQuestion> generateQuizQuestions(String text, int requestedCount) {
        String normalized = clean(text, "").replace('\u00A0', ' ').trim();
        if (normalized.isBlank()) {
            return List.of();
        }

        List<String> keywordPool = extractKeywordPool(normalized);
        List<String> sentences = Arrays.stream(normalized.split("(?<=[.!?])\\s+"))
                .map(String::trim)
                .filter(sentence -> sentence.length() >= 45 && sentence.length() <= 240)
                .toList();

        List<GeneratedQuestion> generated = new ArrayList<>();
        Set<String> seen = new LinkedHashSet<>();
        Random random = new Random(42L);

        for (String sentence : sentences) {
            if (generated.size() >= requestedCount) {
                break;
            }
            String answer = pickAnswerCandidate(sentence);
            if (answer == null || !seen.add(answer.toLowerCase(Locale.ENGLISH))) {
                continue;
            }
            String maskedSentence = sentence.replaceFirst("(?i)\\b" + Pattern.quote(answer) + "\\b", "_____");
            List<String> distractors = pickDistractors(keywordPool, answer, random);
            if (distractors.size() < 3) {
                continue;
            }
            List<String> options = new ArrayList<>(List.of(answer, distractors.get(0), distractors.get(1), distractors.get(2)));
            Collections.shuffle(options, random);
            String correctOption = optionLabelFor(options.indexOf(answer));
            generated.add(new GeneratedQuestion(
                    "Choose the correct term to complete this statement: " + maskedSentence,
                    options.get(0),
                    options.get(1),
                    options.get(2),
                    options.get(3),
                    correctOption,
                    sentence
            ));
        }

        if (generated.size() >= requestedCount) {
            return generated.subList(0, requestedCount);
        }

        List<String> paragraphs = Arrays.stream(normalized.split("(?<=\\.)\\s+"))
                .filter(value -> value.length() > 80)
                .toList();
        for (String paragraph : paragraphs) {
            if (generated.size() >= requestedCount) {
                break;
            }
            List<String> terms = extractKeywordPool(paragraph);
            if (terms.size() < 4) {
                continue;
            }
            String answer = terms.get(0);
            if (!seen.add(answer.toLowerCase(Locale.ENGLISH))) {
                continue;
            }
            List<String> options = new ArrayList<>(terms.subList(0, 4));
            Collections.shuffle(options, random);
            generated.add(new GeneratedQuestion(
                    "According to the uploaded notes, which concept is most strongly highlighted in this passage?",
                    options.get(0),
                    options.get(1),
                    options.get(2),
                    options.get(3),
                    optionLabelFor(options.indexOf(answer)),
                    paragraph.length() > 220 ? paragraph.substring(0, 220) + "..." : paragraph
            ));
        }
        return generated.subList(0, Math.min(generated.size(), requestedCount));
    }

    private List<String> extractKeywordPool(String text) {
        Set<String> stopWords = new HashSet<>(Arrays.asList(
                "the", "and", "for", "with", "that", "this", "from", "into", "about", "their", "there", "which",
                "when", "where", "while", "these", "those", "have", "will", "been", "being", "were", "what",
                "your", "more", "such", "than", "using", "used", "into", "between", "because", "also", "them",
                "they", "them", "some", "each", "very", "into", "over", "under", "through", "across", "method",
                "system", "process", "example", "chapter", "topic", "notes", "important", "definition"
        ));
        LinkedHashSet<String> keywords = new LinkedHashSet<>();
        for (String token : text.split("[^A-Za-z0-9+#.-]+")) {
            String cleaned = token == null ? "" : token.trim();
            if (cleaned.length() < 5) {
                continue;
            }
            if (!cleaned.matches(".*[A-Za-z].*")) {
                continue;
            }
            String normalized = cleaned.toLowerCase(Locale.ENGLISH);
            if (stopWords.contains(normalized)) {
                continue;
            }
            keywords.add(cleaned);
        }
        return new ArrayList<>(keywords);
    }

    private String pickAnswerCandidate(String sentence) {
        for (String token : sentence.split("[^A-Za-z0-9+#.-]+")) {
            String cleaned = token == null ? "" : token.trim();
            if (cleaned.length() >= 6 && cleaned.matches(".*[A-Za-z].*")) {
                String lower = cleaned.toLowerCase(Locale.ENGLISH);
                if (!Set.of("because", "through", "between", "important", "example", "system", "process").contains(lower)) {
                    return cleaned;
                }
            }
        }
        return null;
    }

    private List<String> pickDistractors(List<String> keywordPool, String answer, Random random) {
        List<String> choices = new ArrayList<>();
        for (String candidate : keywordPool) {
            if (candidate.equalsIgnoreCase(answer)) {
                continue;
            }
            if (Math.abs(candidate.length() - answer.length()) > 8) {
                continue;
            }
            choices.add(candidate);
        }
        Collections.shuffle(choices, random);
        return choices.stream().distinct().limit(3).toList();
    }

    private String optionLabelFor(int index) {
        return switch (index) {
            case 0 -> "A";
            case 1 -> "B";
            case 2 -> "C";
            default -> "D";
        };
    }

    private String normalizeOption(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        String normalized = value.trim().toUpperCase(Locale.ENGLISH);
        return Set.of("A", "B", "C", "D").contains(normalized) ? normalized : null;
    }

    private void addNotification(String recipientRole, String recipientEmail, String title, String message, String category, String linkUrl, String sourceType, Long sourceId, LocalDateTime scheduledFor) {
        if (recipientEmail == null || recipientEmail.isBlank()) {
            return;
        }

        PortalNotification notification = new PortalNotification();
        notification.setRecipientRole(recipientRole);
        notification.setRecipientEmail(recipientEmail);
        notification.setTitle(title);
        notification.setMessage(message);
        notification.setCategory(category);
        notification.setLinkUrl(linkUrl);
        notification.setSourceType(sourceType);
        notification.setSourceId(sourceId);
        notification.setScheduledFor(scheduledFor != null ? scheduledFor : LocalDateTime.now());
        notification.setCreatedAt(LocalDateTime.now());
        portalNotificationRepository.save(notification);
    }

    private List<Student> resolveTeacherStudents(Teacher teacher) {
        if (teacher == null) {
            return List.of();
        }
        ClassRoom classRoom = resolveTeacherClassRoom(teacher);
        if (classRoom != null) {
            return studentRepository.findByClassRoom(classRoom);
        }
        if (teacher.getAdmin() != null) {
            return studentRepository.findByAdmin(teacher.getAdmin());
        }
        return List.of();
    }

    private ClassRoom resolveTeacherClassRoom(Teacher teacher) {
        if (teacher == null) {
            return null;
        }
        if (teacher.getClassRoom() != null && teacher.getClassRoom().getId() != null) {
            return teacher.getClassRoom();
        }
        for (Timetable entry : timetableRepository.findByTeacher(teacher)) {
            if (entry != null && entry.getClassRoom() != null && entry.getClassRoom().getId() != null) {
                return entry.getClassRoom();
            }
        }
        return null;
    }

    private double estimateAttendanceScore(Student student) {
        List<TeacherAttendanceEntry> entries = teacherAttendanceEntryRepository.findByStudentOrderByMarkedAtDesc(student);
        if (entries.isEmpty()) {
            return 68.0;
        }

        long present = entries.stream().filter(entry -> entry.getStatus() != null && entry.getStatus().equalsIgnoreCase("present")).count();
        return Math.max(35.0, (present * 100.0) / entries.size());
    }

    private double estimateExamAbsencePenalty(Student student) {
        List<ExamAttendance> attendances = examAttendanceRepository.findAll().stream()
                .filter(row -> row.getStudent() != null && student.getId() != null && student.getId().equals(row.getStudent().getId()))
                .toList();
        if (attendances.isEmpty()) {
            return 0.0;
        }
        long absent = attendances.stream().filter(row -> row.getStatus() != null && row.getStatus().equalsIgnoreCase("absent")).count();
        return Math.min(absent * 8.0, 24.0);
    }

    private StoredFile storeExamFile(MultipartFile file) {
        String originalName = StringUtils.cleanPath(Objects.requireNonNullElse(file.getOriginalFilename(), ""));
        if (originalName.isBlank()) {
            return null;
        }

        String extension = "";
        if (originalName.contains(".")) {
            extension = originalName.substring(originalName.lastIndexOf('.'));
        }

        if (!isAllowedExamFile(file.getContentType(), extension, originalName)) {
            return null;
        }

        try {
            Path dir = STATIC_ROOT.resolve(EXAM_UPLOAD_DIR);
            Files.createDirectories(dir);
            String storedName = UUID.randomUUID() + extension;
            Path target = dir.resolve(storedName);
            Files.copy(file.getInputStream(), target, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            return new StoredFile(originalName, storedName, "/uploads/exams/" + storedName, file.getContentType(), file.getSize());
        } catch (IOException e) {
            return null;
        }
    }

    private boolean isAllowedExamFile(String contentType, String extension, String originalName) {
        String normalizedExtension = clean(extension, "").toLowerCase(Locale.ENGLISH);
        String normalizedName = clean(originalName, "").toLowerCase(Locale.ENGLISH);
        Set<String> allowed = Set.of(".pdf", ".doc", ".docx", ".ppt", ".pptx");
        if (allowed.stream().noneMatch(normalizedExtension::endsWith) && !normalizedExtension.isBlank()) {
            return false;
        }
        if (contentType == null || contentType.isBlank()) {
            return true;
        }
        return Set.of(
                "application/pdf",
                "application/msword",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/vnd.ms-powerpoint",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        ).contains(contentType.toLowerCase(Locale.ENGLISH)) || normalizedName.endsWith(".pdf") || normalizedName.endsWith(".doc")
                || normalizedName.endsWith(".docx") || normalizedName.endsWith(".ppt") || normalizedName.endsWith(".pptx");
    }

    private String seatLabel(int index) {
        int row = ((index - 1) / 4) + 1;
        int seat = ((index - 1) % 4) + 1;
        return "Row " + row + " Seat " + seat;
    }

    private String clean(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value.trim();
    }

    public record StudentSeatView(int serialNo, Student student, String rollNo, String seatLabel) {}
    public record StudentRiskView(Student student, long score, String band, String reason) {}
    private record GeneratedQuestion(String questionText,
                                     String optionA,
                                     String optionB,
                                     String optionC,
                                     String optionD,
                                     String correctOption,
                                     String explanation) {}
    private record StoredFile(String originalName, String storedName, String webPath, String contentType, Long size) {}
}
